---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
#import libries:
library(dplyr)
library(Seurat)
library(patchwork)
```

```{r}
# Write the data to a TSV file
df <- read.table("C:\\Users\\LENOVO\\Dropbox\\miniProject\\GSE225172_sc_MT_Babraham_Blood_aging\\sc_MT_Babraham_Blood_aging.txt", header = TRUE)
class(df)
# Assuming 'df' is your data.frame
library(Matrix)

# Convert the data.frame to a sparse matrix
md <- Matrix(nrow = count(rownames(df)), ncol = count(colnames(df)), data =as.matrix(df)[,], sparse = TRUE)
md <- as(md, "dgCMatrix") # by default, Matrix() returns dgCMatrix
class(md)
```
```{r}
####mitchodrial gene
library("EnsDb.Mmusculus.v79")

# Convert from ensembl.gene to gene.symbol
geneIDsconverted <- ensembldb::select(EnsDb.Mmusculus.v79, keys= row.names(md), keytype = "GENEID", columns = c("SYMBOL","GENEID"))
#חסרים עוד ~8,000 גנים ככל הנראה זה פסאודוגנים lncRNA
mt_genes <- geneIDsconverted[grep("^mt-", geneIDsconverted$SYMBOL), ]
```

```{r}
# Combine columns into a list
combined_list <- paste(mt_genes$SYMBOL, mt_genes$GENEID, sep = "-")
md_row=row.names(md)
for (i in 1:nrow(mt_genes)){
  for(j in 1:nrow(md)){
    if (mt_genes$GENEID[i] == md_row[[j]]){
        md_row[[j]]=combined_list[i]
    }
  }
}
rownames(md) <- md_row
```

```{r}
# Initialize the Seurat object with the raw (non-normalized data).
data1<- CreateSeuratObject(counts = md, project = "data1", min.cells = 3, min.features = 200)
data1
data1[["percent.mt"]] <- PercentageFeatureSet(data1, pattern = "^mt-")
# Visualize QC metrics as a violin plot
VlnPlot(data1, features = c("nFeature_RNA", "nCount_RNA","percent.mt"), ncol = 3)
```

```{r}
data1 <- subset(data1, subset = nFeature_RNA > 1000 & nFeature_RNA < 4500 &  nCount_RNA<750000 & percent.mt < 6)
```

```{r}
#Normalizing the data
data1 <-  SCTransform(data1, vst.flavor = "v2", verbose = FALSE)

```

```{r}

```

```{r}
#Perform linear dimensional reduction
data1 <- RunPCA(data1, features = VariableFeatures(object = data1))
# Examine and visualize PCA results a few different ways
print(data1[["pca"]], dims = 1:5, nfeatures = 5)

```

```{r}
#analysis on 2 first dims- למה רק את השתיים הראשונים???
VizDimLoadings(data1, dims = 1:2, reduction = "pca")
#נותנים יותר שונות בין התאים 
```

```{r}
#analysis the main feature
DimPlot(data1, reduction = "pca") + NoLegend()
```

```{r}
#heatmap for main first feature
DimHeatmap(data1, dims = 1, cells = 500, balanced = TRUE)
```

```{r}
#heatmap for main 15 feature- למה מדפיסים שוב עבור 15 אפשר לוותר על ההדפסה  הקודמנת???
DimHeatmap(data1, dims = 1:15, cells = 500, balanced = TRUE)
```

```{r}
#optimal number of clustering
ElbowPlot(data1)
```

```{r}
#Cluster the cells:
data1 <- FindNeighbors(data1, dims = 1:10)
data1 <- FindClusters(data1, resolution = 0.5)
# Look at cluster IDs of the first 5 cells
head(Idents(data1), 5)
```

```{r}
#Run non-linear dimensional reduction (UMAP/tSNE):
data1 <- RunUMAP(data1, dims = 1:10)
# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
DimPlot(data1, reduction = "umap")
#save the data:
saveRDS(data1, file = "C:\\Users\\LENOVO\\Dropbox\\miniProject\\data1_tutorial.rds")
#האם ניתן לשפר את החלוקה לקלסטרים????
```

```{r}
DefaultAssay(data1) <- "SCT"
data1 <- PrepSCTFindMarkers(data1)
```

```{r}
# find all markers of cluster 0
cluster0.markers <- FindMarkers(data1, ident.1 = 0)
clus0 <- cluster0.markers[cluster0.markers$p_val_adj<0.05 & cluster0.markers$avg_log2FC >0,]
row<-row.names(clus0)
write.csv(row,file = "C:\\Users\\LENOVO\\Dropbox\\miniProject\\row0.csv")
# find all markers of cluster 1
cluster1.markers <- FindMarkers(data1, ident.1 = 1)
clus1<-cluster1.markers[cluster1.markers$p_val_adj<0.05 & cluster1.markers$avg_log2FC >0,]
row<-row.names(clus1)
write.csv(row,file = "C:\\Users\\LENOVO\\Dropbox\\miniProject\\row1.csv")
# find all markers of cluster 2
cluster2.markers <- FindMarkers(data1, ident.1 = 2)
clus2<-cluster2.markers[cluster2.markers$p_val_adj<0.05 & cluster2.markers$avg_log2FC >0,]
row<-row.names(clus2)
write.csv(row,file = "C:\\Users\\LENOVO\\Dropbox\\miniProject\\row2.csv")
# find all markers of cluster 3
cluster3.markers <- FindMarkers(data1, ident.1 = 3)
clus3<-cluster3.markers[cluster3.markers$p_val_adj<0.05 & cluster3.markers$avg_log2FC >0,]
row<-row.names(clus3)
write.csv(row,file = "C:\\Users\\LENOVO\\Dropbox\\miniProject\\row3.csv")
# find all markers of cluster 4
cluster4.markers <- FindMarkers(data1, ident.1 = 4)
clus4<-cluster4.markers[cluster4.markers$p_val_adj<0.05 & cluster4.markers$avg_log2FC >0,]
row<-row.names(clus4)
write.csv(row,file = "C:\\Users\\LENOVO\\Dropbox\\miniProject\\row4.csv")
# find all markers of cluster 0&1
cluster01.markers <- FindMarkers(data1, ident.1 = c(0,1))
clus01<-cluster01.markers[cluster01.markers$p_val_adj<0.05 & cluster01.markers$avg_log2FC >0,]
row<-row.names(clus01)
write.csv(row,file = "C:\\Users\\LENOVO\\Dropbox\\miniProject\\row01.csv")
```

```{r}

new.cluster.ids <- c("B cells", "B cells", "CD4+T cells", "CD8+T cells", "CD14+ monocyte")
names(new.cluster.ids) <- levels(data1)
data1 <- RenameIdents(data1, new.cluster.ids)
DimPlot(data1, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()
```

```{r}
df<-read.csv("C:\\Users\\LENOVO\\Dropbox\\miniProject\\fix_annotations_ages.csv")
rownames(df) <- df$Sample.ID
row.names(df)
```

```{r}
# Merge the Seurat object with the data frame
#print meta data before 
print(data1@meta.data)
#try<- AddMetaData(try,df$cell.type,col.name ="cell_type")
#data1<- AddMetaData(data1,df$Cell.type,col.name = 'cell.type')
#data1<- AddMetaData(data1,df$Chronological_age,col.name = 'Chronological_age')
# Add 'Cell.type' metadata to the Seurat object
data1 <- AddMetaData(data1, metadata = df[, "Cell.type", drop = FALSE], col.name = "cell.type")

# Add 'Chronological_age' metadata to the Seurat object
data1 <- AddMetaData(data1, metadata = df[, "Chronological_age", drop = FALSE], col.name = "Chronological_age")
#after:
print(data1@meta.data)
```
```{r}
#save data1 after all
saveRDS(data1, file = "C:\\Users\\LENOVO\\Dropbox\\miniProject\\data1_after_all.rds")
```
```{r}
 table(data1$seurat_clusters, data1$cell.type)
```
```{r}
meAge= read.csv("C:\\Users\\LENOVO\\Dropbox\\miniProject\\fix_meAge.csv")
head(meAge)
tail(meAge)
```
```{r}
data1 <- AddMetaData(data1, metadata = meAge[,"v1", drop = FALSE], col.name = "file_name")

# Add 'Chronological_age' metadata to the Seurat object
data1 <- AddMetaData(data1, metadata = meAge[, "v2", drop = FALSE], col.name = "methyl_precent")
#after:
print(data1@meta.data)
```

